name 'git-clone'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures git-clone'
long_description 'Installs/Configures git-clone'
version '0.1.0'
